# Generated by Django 3.2.12 on 2023-09-26 11:17
from  Header.models  import siteList
from  Header import models
from django.db import migrations


def load_data(apps, schema_editor):
    siteList.objects.all().delete()
    siteList.objects.create(name="Donate",baseroot="/", img="", active=True)
    siteList.objects.create(name="IT",baseroot="/it", img="", active=True)
    siteList.objects.create(name="Civil",baseroot="/civil", img="", active=True)

class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(load_data),
    ]
