# Generated by Django 4.2.4 on 2023-09-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_codeverification_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='createDate',
            field=models.CharField(default='09/06/23 20:53:30', max_length=300),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expiredDate',
            field=models.CharField(default='09/06/23 21:08:30', max_length=300),
        ),
    ]
