# Generated by Django 4.2.4 on 2023-09-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_codeverification_createdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalqualification',
            old_name='institute_name',
            new_name='institute',
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='createDate',
            field=models.CharField(default='09/06/23 20:58:02', max_length=300),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expiredDate',
            field=models.CharField(default='09/06/23 21:13:02', max_length=300),
        ),
    ]
