# Generated by Django 4.2.4 on 2023-09-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_rename_institute_name_educationalqualification_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='createDate',
            field=models.CharField(default='09/06/23 21:20:44', max_length=300),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expiredDate',
            field=models.CharField(default='09/06/23 21:35:44', max_length=300),
        ),
        migrations.AlterField(
            model_name='educationalqualification',
            name='institute',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
