# Generated by Django 3.2.18 on 2023-09-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_auto_20230903_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='createDate',
            field=models.CharField(default='09/04/23 17:46:11', max_length=300),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expiredDate',
            field=models.CharField(default='09/04/23 18:01:11', max_length=300),
        ),
    ]
