# Generated by Django 3.2.18 on 2023-09-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0013_auto_20230916_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='createDate',
            field=models.CharField(default='09/16/23 06:25:13', max_length=300),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expiredDate',
            field=models.CharField(default='09/16/23 06:40:13', max_length=300),
        ),
    ]
