# Generated by Django 3.2.18 on 2023-09-04 22:46

import Civil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Civil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservices',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=Civil.models.upload_to_service),
        ),
    ]
