# Generated by Django 3.2.12 on 2023-09-22 08:52

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import footer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Header', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=footer.models.upload_to_icons)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='footerSocialIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('link', models.URLField(max_length=300)),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=footer.models.upload_to_icons)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('siteList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Header.sitelist')),
            ],
        ),
        migrations.CreateModel(
            name='footerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Header.sitelist')),
            ],
        ),
        migrations.CreateModel(
            name='footerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('link', models.CharField(default='/', max_length=300)),
                ('order', models.CharField(blank=True, default=footer.models.order_id, max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('footerSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footer.footersection')),
            ],
        ),
        migrations.CreateModel(
            name='footerHeadOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_address', models.CharField(max_length=300)),
                ('usa_email', models.EmailField(max_length=300)),
                ('usa_phone', models.CharField(max_length=300)),
                ('usa_fax', models.CharField(max_length=300)),
                ('uk_address', models.CharField(max_length=300)),
                ('uk_email', models.EmailField(max_length=300)),
                ('uk_phone', models.CharField(max_length=300)),
                ('uk_fax', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('siteList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Header.sitelist')),
            ],
        ),
    ]
