# Generated by Django 4.2.4 on 2023-09-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
