# Generated by Django 3.2.12 on 2023-09-04 19:25

import Header.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Header', '0003_alter_navbar_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=(30, 30), upload_to=Header.models.upload_to_icons),
        ),
    ]
