# Generated by Django 3.2.12 on 2023-09-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderit',
            name='project_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orderit',
            name='total_online_paid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orderit',
            name='total_price',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
