# Generated by Django 3.2.12 on 2023-09-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0002_auto_20230912_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderit',
            name='total_offline_paid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
